### ISSUE TITLE
"Stay" at the end of the mission

### ISSUE THREAD

**Issue by lobe7** [buczek-j/usrp-utils#14]
Add a number of action lines to the end of the CSV file that keep the UAVs locations and tx power unchanged for several iterations (1 minute)

**Comment by lobe7** [comment]
Add an option to stay for a timeout at the end of the mission. 

We will use this option when testing the performance of single line .csv BR and NC.

**Comment by buczek-j** [comment]
added test_timeout and use_timeout flags
