### ISSUE TITLE
Create a "synch code" script that copies the code from a ground pc onto the UAV without internet access

### ISSUE THREAD

**Issue by lobe7** [buczek-j/usrp-utils#8]
Base the synch code on ssh and rsync -au (which copies updated files only) 

see:
https://unix.stackexchange.com/questions/14191/scp-without-replacing-existing-files-in-the-destination

https://phoenixnap.com/kb/how-to-rsync-over-ssh

**Comment by buczek-j** [comment]
Made file [clone.sh](https://github.com/buczek-j/usrp-utils/blob/4fda6f711dbab309cbe149c201d39e668140beda/clone.sh)

also used:
https://help.ubuntu.com/community/rsync
